### ISSUE TITLE
Only about half of config'd words are being blocked

### ISSUE THREAD

**Issue by gmalone** [MC-Resources-Store/message-blocker#1]
Hi, I'm running Paper 1.14.4 server (latest). And the latest MessageBlocker 1.0.1 from SpigotMC.

I'm trying to block a stream of messages from WorldEdit plugin that happen during a scripted series of schematic loads and pastes.

About half of the config'd messages are being properly blocked.  The other half not, though I've tried both "starts_with" and "contains" flags on those.

The config (this stupid text editor is turning the hyphens into bullets):
`
blocked:
  - message: 'Blocks processed'
    mode: 'starts_with'
    ignore_case: true
    bypass_permission:
  - message: 'Running paste'
    mode: 'starts_with'
    ignore_case: true
    bypass_permission:
  - message: 'Running load'
    mode: 'starts_with'
    ignore_case: true
    bypass_permission:
  - message: 'Job'
    mode: 'starts_with'
    ignore_case: true
    bypass_permission:
_(These next ones are not being blocked:)_
  - message: 'The clipboard has been pasted at'
    mode: 'starts_with'
    ignore_case: true
    bypass_permission:
  - message: 'Paste it with'
    mode: 'contains'
    ignore_case: true
    bypass_permission:
  - message: 'blocks affected'
    mode: 'contains'
    ignore_case: true
    bypass_permission:
  - message: 'biomes affected'
    mode: 'contains'
    ignore_case: true
    bypass_permission:
  - message: 'entities affected'
    mode: 'contains'
    ignore_case: true
    bypass_permission:
`

I've indicated where in the list the messages stop being blocked.  You'll note I've grouped those at the bottom of the config, though I've tested them at the start as well with same result.

Here is an image of the output in chat.
![Annotation 2020-02-06 172159](https://user-images.githubusercontent.com/3749543/73990374-3077a400-4906-11ea-88e6-3f9d1967ca0e.png)

I've also tried adding delays between each execution of the WorldEdit commands, in case the async speed was causing some to get by without filtering.  No change in results.

Any thoughts?
Many thanks for the assist.

**Comment by Krymonota** [comment]
It appears to me that no message from WorldEdit is blocked. The messages that are blocked are sent by AsyncWorldEdit. I'll look into it.

**Comment by gmalone** [comment]
I apologize for not mentioning AsyncWorldEdit.  Duh!  I appreciate you looking into it very much.  Thanks!

**Comment by Krymonota** [comment]
I was able to find the cause and an appropriate solution to this issue. An update has been released that addresses this issue. Please let me know if any other problems occur. Thank you for reporting this bug 🙂

**Comment by gmalone** [comment]
Sa-weet!  Thanks @Krymonota .  I'll watch for an update on Spigot.  Or here.  And, I'll let you know how it goes w/ the fix.  Thanks again.

**Comment by gmalone** [comment]
Works PERFECTLY.  It's so nice to see that plugin noise disappear from chat.  Thank.  Will donate!

**Comment by Krymonota** [comment]
That's great to hear and thanks for donating!
